Update DB Migration docs
NASA-AMMOS/aerie-docs pull request #201
Opened 2024-12-11 18:30 UTC by Mythicaeda

Docs PR for https://github.com/NASA-AMMOS/aerie/pull/1617.

Moves the old docs to an unlisted subpage that is linked from the updated docs (and links back to the updated docs).

2025-01-23 20:42 UTC, dandelany requested changes
Thanks, looking good @Mythicaeda - just one change to an example command here (see related notes on the aerie PR [here](https://github.com/NASA-AMMOS/aerie/pull/1617#pullrequestreview-2570956942) )

2025-01-23 20:42 UTC, dandelany commented on docs/deployment/advanced-database-migrations.mdx
>  export PATH="$HOME/path/to/deployment:$PATH"
This comment belongs on **line 22** above, I can't put it there because Github...

This command `python aerie_db_migration.py` is no longer a valid call to the script due to the newly added subcommands - we should replace it with the new minimum command. Since I think some values from the env file are required, that would be something like  `aerie_db_migration.py migrate -e .env`, correct?

2025-01-28 22:16 UTC, Mythicaeda commented on docs/deployment/advanced-database-migrations.mdx
>  export PATH="$HOME/path/to/deployment:$PATH"
`-e .env` isn't required, but the subcommand is. I've updated the docs to reflect this.

2025-01-29 00:55 UTC, dandelany approved these changes
Thanks, approved! Let's hold off on merging this until next release for least confusion, I will merge it at release time.

2025-02-12 22:34 UTC, merged